### ISSUE TITLE
一处疑惑

### ISSUE THREAD

**Issue by pikeszfish** [sixu05202004/flaskblog#2]
你好。
最近学flask，在看这份blog的代码，其中有一处看不太懂，class Post中有一个函数
def _url(self):
        return url_for('post', name=self.post_name)
该url_for的'post'我在view.py中没有找到def post()这个视图函数 
不知道是不是我url_for的用法没有掌握还怎么样的，特来请教

**Comment by sixu05202004** [comment]
不好意思，给你造成困惑，这部分代码已经是很久以前的，不适用现在版本的flask以及一些插件，有时间会更新代码。
